### ISSUE TITLE
Add note on changing the default keybindings

### ISSUE THREAD

**Issue by gerazov** [plainas/icl#1]
Great tool :+1: Maybe adding a note on changing the default keybindings in the README would be useful - albeit trivial for `^t` but where can I turn off the `<tab>` binding? :sweat_smile:

**Comment by pedrofyndiq** [comment]
Good point.

> but where can I turn off the <tab> binding?

can you elaborate?

**Comment by plainas** [comment]
good point.

> but where can I turn off the <tab> binding?

can you elaborate on this? Which tab binding?

**Comment by gerazov** [comment]
For some reason pressing `<tab>` triggers icl.

**Comment by plainas** [comment]
Which shell do you use?

**Comment by gerazov** [comment]
I'm on `zsh`.

**Comment by plainas** [comment]
Did you install with the quick install script provided in the readme? Or did you add your keybing manually?

I have just tested installing acl on a clean container with zsh and couldn't reproduce the problem you described.

**Comment by gerazov** [comment]
Yes I used your script but changed the key binding like so:
```sh
f_run_icl(){
    icl_OUTPUT=$(icl)
    print -z $icl_OUTPUT
    zle accept-line # no idea if this is the way it's done
}

zle -N w_run_icl f_run_icl # create a widget
bindkey ^i w_run_icl
```
This still triggers the `icl` even when it's the only code in my `.zshrc`.

**Comment by cibinmathew** [comment]
Ctrl-i is tab equivalent in some shells

**Comment by plainas** [comment]
I am still unable to reproduce that problem. Try installing on a clean system, inside a docker or lxd container. Does the problem persist. Which terminal emulator do you use?

**Comment by gerazov** [comment]
> Ctrl-i is tab equivalent in some shells

This solved it - it now works as expected! Thanks :+1:
