### ISSUE TITLE
Escape key to exit icl

### ISSUE THREAD

**Issue by cibinmathew** [plainas/icl#3]
**Feature Request**
Exit using escape key as an alternative binding in addition to Ctrl-c

Would it be possible to add something here or is it handled somewhere
https://github.com/plainas/icl/blob/c0aefca8b7f2d8c2d2ebb18239a50475f6fcec7c/icl.py#L186-L193

**Comment by plainas** [comment]
Hey Mathew.

Yes, that is where it is.
The terminal needs to be restored to previous state like it's done on line 127 onwards. 

if you do implement it, pull requests are welcome.

Probably time to wrap terminal restoration into a funciton since it will already be used in three different places.

**Comment by cibinmathew** [comment]
Let me raise a quick PR without much changes to add escape key as well
